[package]
name = "pkr-cfr-bench"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
pkr-cfr = { workspace = true }
pkr-contracts = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "table"
harness = false

[[bench]]
name = "dcfr"
harness = false

[[bench]]
name = "metrics"
harness = false
