[package]
name = "pkr-subgame"
version.workspace = true
edition.workspace = true

[dependencies]
pkr-contracts = { workspace = true }
pkr-core = { workspace = true }
pkr-eval = { workspace = true }
pkr-abstraction = { workspace = true }
pkr-cfr = { workspace = true }
rayon = { workspace = true }
foldhash = { workspace = true }
