#!/usr/bin/env bash
set -euo pipefail

# ------------------------------------------------------------
# GPU-accelerated training pipeline for pkr-sota
# Requires: Rust toolchain, Metal-capable GPU (Apple Silicon)
# ------------------------------------------------------------

# Number of threads for Rayon CPU pool (set to number of P-cores on M1)
export RAYON_NUM_THREADS=4   # M1 has 4 performance cores; adjust if needed

# Monte Carlo sample count for EHS (higher = better abstraction quality, slower)
export EHS_SAMPLES=1000

# Build the entire workspace with GPU feature and release optimizations
echo "Building workspace with GPU support..."
cargo build --release --features gpu

# ------------------------------------------------------------
# Step 1: Generate the 5-card hand rank lookup table
# ------------------------------------------------------------
echo "Generating hand rank table..."
cargo run --release --features gpu --bin pkr-abstraction-precompute -- table hand_ranks.bin

# ------------------------------------------------------------
# Step 2: Generate centroids (for hand-strength clustering)
# ------------------------------------------------------------
echo "Generating centroids (10k samples, 200 clusters)..."
cargo run --release --features gpu --bin pkr-abstraction-precompute -- centroids 10000 200 centroids.bin

# (Optional) Per-street centroids can be generated by changing the board length
# e.g., for turn: use cards[2..6] in centroids command (not currently supported via CLI)
# For now we use the same centroids for all streets (default behaviour).

# ------------------------------------------------------------
# Step 3: Generate flop buckets (board texture clustering)
# ------------------------------------------------------------
echo "Generating flop buckets (200 buckets)..."
cargo run --release --features gpu --bin pkr-abstraction-precompute -- flop_buckets 200 hand_ranks.bin flop_buckets.bin

# ------------------------------------------------------------
# Step 4: Generate precomputed abstraction tables
# ------------------------------------------------------------
echo "Generating preflop abstraction table..."
cargo run --release --features gpu --bin pkr-abstraction-precompute -- preflop_table centroids.bin hand_ranks.bin preflop_abstraction.bin

echo "Generating flop abstraction table..."
cargo run --release --features gpu --bin pkr-abstraction-precompute -- abstraction centroids.bin hand_ranks.bin abstraction.bin

echo "Generating turn abstraction table..."
cargo run --release --features gpu --bin pkr-abstraction-precompute -- turn_table centroids.bin hand_ranks.bin turn_abstraction.bin

# (Optional) River table can be generated similarly, but currently not implemented
# in the precompute binary (river uses MC fallback).

# ------------------------------------------------------------
# Step 5: Train the blueprint with PCFR+ and GPU-accelerated table
# ------------------------------------------------------------
echo "Starting training with GPU acceleration..."
cargo run --release --features gpu --bin pkr-trainer -- \
  --iterations 1000 \
  --threads 4 \
  --centroids centroids.bin \
  --preflop-table preflop_abstraction.bin \
  --flop-table abstraction.bin \
  --turn-table turn_abstraction.bin \
  --flop-buckets flop_buckets.bin \
  --rank-table hand_ranks.bin \
  --output blueprint.bin

echo "Training complete. Blueprint saved to blueprint.bin"
