[package]
name = "pkr-export"
version.workspace = true
edition.workspace = true

[dependencies]
pkr-core = { workspace = true }
pkr-contracts = { workspace = true }
pkr-cfr = { workspace = true }
thiserror = { workspace = true }
bytemuck = { workspace = true }
foldhash = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tempfile = "3"
