[package]
name = "pkr-abstraction"
version.workspace = true
edition.workspace = true

[dependencies]
pkr-contracts = { workspace = true }
pkr-core = { workspace = true }
pkr-eval = { workspace = true }
amx-rs = "0.0.3" # Apple Silicon AMX intrinsics
rayon = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
