[package]
name = "pkr-abstraction"
version.workspace = true
edition.workspace = true

[[bin]]
name = "pkr-abstraction-precompute"
path = "src/bin/precompute.rs"

[dependencies]
pkr-contracts = { workspace = true }
pkr-core = { workspace = true }
pkr-eval = { workspace = true }
rayon = { workspace = true }
rand = { workspace = true }
tracing = { workspace = true }
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
