[package]
name = "pkr-runtime"
version.workspace = true
edition.workspace = true

[dependencies]
pkr-core = { workspace = true }
pkr-contracts = { workspace = true }
pkr-export = { workspace = true }
memmap2 = { workspace = true }
thiserror = { workspace = true }
bytemuck = { workspace = true }

[dev-dependencies]
tempfile = "3"
