[package]
name = "pkr-cfr"
version.workspace = true
edition.workspace = true

[dependencies]
pkr-contracts = { workspace = true }
pkr-abstraction = { workspace = true }
pkr-core = { workspace = true }
pkr-eval = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
papaya = { workspace = true }
foldhash = { workspace = true }
wgpu = { version = "29.0.3", optional = true }
bytemuck = { workspace = true }
pollster = "0.3"

[features]
default = ["gpu"]
gpu = ["wgpu"]
