[package]
name = "pkr-cfr"
version.workspace = true
edition.workspace = true

[dependencies]
pkr-contracts = { workspace = true }
pkr-abstraction = { workspace = true }
pkr-core = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
tracing = { workspace = true }
dashmap = { workspace = true }
papaya = { workspace = true }
